### ISSUE TITLE
s/functionnal/functional/

### ISSUE THREAD

**Issue by alexisLefebvre** [symfony/test-pack#1]
In this project's description and `composer.json` file, it is written _functionnal_, I think that it should be changed to _functional_ since I can't find any proof that the word _functionnal_ with 2 `n` exist.

**Comment by fabpot** [comment]
Can you submit a PR?

**Comment by alexisLefebvre** [comment]
Yes, please see #2.

**Comment by alexisLefebvre** [comment]
@fabpot Please note that the error is still in the project's description:

> ![capture d ecran de 2018-03-20 11-56-51](https://user-images.githubusercontent.com/2071331/37658264-6a4c08ec-2c4d-11e8-8ea8-17bc671764c5.png)

**Comment by nicolas-grekas** [comment]
project description updated
