### ISSUE TITLE
Server variable are different than normal way

### ISSUE THREAD

**Issue by Elikill58** [symfony/test-pack#22]
I'm adding test to my project. I encouter multiple issue, but the most important one is about the strange way that phpunit load the symfony website.

For example, in normal env, the variable `$_SERVER["CONTEXT_DOCUMENT_ROOT"]` exists, but not with test env.
Also, there is no session when doing request, which means we can't same something on session (as user does when they login), or even get the token manager.

When using `$client->getContainer()->get("security.csrf.token_manager")->getToken("thing")` we have a message as "Currently no session available".

Why is there so much differences between both, and not simply the same website just load with `ENV=test` ?

**Comment by nicolas-grekas** [comment]
Wrong repo I guess, this has nothing to do with test-pack.

**Comment by Elikill58** [comment]
Ok but where should I post it?

**Comment by nicolas-grekas** [comment]
See https://symfony.com/support, section "Open Source".
About CONTEXT_DOCUMENT_ROOT, stackoverflow explains what this is: an Apache2-specific thing, nothing standard.
