### ISSUE TITLE
Class PHPUnit\Framework\TestCase not found and could not be autoloaded.

### ISSUE THREAD

**Issue by koftikes** [symfony/test-pack#6]
When I use Symfony 4.1 and PhpStan 0.10
In case:
Adding phpunit/phpunit as a dependency is discouraged in favor of Symfony's PHPUnit Bridge.

Instead:
Remove it now: composer remove --dev phpunit/phpunit
Use Symfony's bridge: composer require --dev phpunit
i got next erors:
Class PHPUnit\Framework\TestCase not found and could not be autoloaded.
Class PHPUnit\Framework\TestCase was not found while trying to analyse it - autoloading is probably not configured properly.
This hapens becouse phpunit not install before run a tests.
you also can see next topic in [PhpStan repo](https://github.com/phpstan/phpstan/issues/694)

**Comment by carlospauluk** [comment]
Same here. Weird!

**Comment by dvdknaap** [comment]
Got the same error.
Haven't found any solution yet.

**Comment by shehi** [comment]
This shit is still happening. Any fixes?!

**Comment by rafrsr** [comment]
I have the same problem, I need install phpunit manually and ignore the warning otherwise phpunit does not install.

**Comment by ribeiropaulor** [comment]
The same here.

**Comment by lucinda-marchant** [comment]
If you run php bin/phpunit all the PHPUnit classes will install. Easy workaround.

**Comment by jfsenechal** [comment]
> If you run php bin/phpunit all the PHPUnit classes will install. Easy workaround.

Nothing works for me,

**Comment by CharlyPoppins** [comment]
Try to create  a `phpstan.neon` file in your project dir root and define the phpunit autoload file
```
# phpstan.neon
parameters:
  autoload_files:
    - bin/.phpunit/phpunit-7.5/vendor/autoload.php
```

**Comment by neverdieTRX** [comment]
> 
> 
> If you run php bin/phpunit all the PHPUnit classes will install. Easy workaround.

worked for me too

**Comment by jfsenechal** [comment]
Me too Thank you

**Comment by normanlolx** [comment]
For me it was `composer require phpunit/phpunit` 😅

**Comment by bodik** [comment]
here my 2 cents https://github.com/symfony/symfony/issues/36202#issuecomment-643751206

**Comment by camerongreen** [comment]
I'm just writing my first test on my first pure Symfony app, and I just couldn't find this file.  You should probably be able to write a test when getting started with a framework without going to StackOverflow and a github issues page.  Putting a neon file in with the version seems like a bit of a maintenance issue.  Running phpunit seems hacky.  Anyway will do, but think it would be good to come up with a better solution.
