### ISSUE TITLE
Comand "composer rem symfony/test-pack" removes the file "/config/bootstrap.php"

### ISSUE THREAD

**Issue by nickicool** [symfony/test-pack#8]
May be bug. 

Run comand `composer rem symfony/test-pack` removes the file `/config/bootstrap.php`. 

To repeat the bug just create new project `composer create-project symfony/website-skeleton my-project`  - and all.

Symfony 4.3.0

**Comment by k00ni** [comment]
What is the status here?

**Comment by nicolas-grekas** [comment]
Closing as packs should be unpacked now.
